-- =============================================================================
-- CBACT04C Gold Layer DDL
-- =============================================================================
-- Catalog:  carddemo
-- Schema:   gold
-- Purpose:  Audit trail for interest charges generated by CBACT04C
--
-- This table replaces the COBOL DISPLAY statements that printed each processed
-- record and WS-TOTAL-INT totals to SYSOUT. It provides per-category granularity
-- for downstream audit, reconciliation, and reporting.
--
-- Granularity: one row per (account, transaction category) per run_date.
-- Partitioned by (charge_year, charge_month) to support monthly cost queries.
-- =============================================================================

USE CATALOG carddemo;
USE SCHEMA gold;

-- ---------------------------------------------------------------------------
-- 5.x carddemo.gold.interest_charges
-- Replaces: COBOL SYSOUT DISPLAY statements (paragraph 1300-B-WRITE-TX)
-- Populated by: CBACT04C pipeline (src/account_updater.py: write_gold_interest_charges)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS carddemo.gold.interest_charges (
  -- Transaction linkage
  tran_id                 STRING         NOT NULL
                          COMMENT 'Generated TRAN-ID: PARM-DATE(YYYYMMDD) + WS-TRANID-SUFFIX(6 digits)',
  acct_id                 BIGINT         NOT NULL
                          COMMENT 'Account this interest was charged to (TRANCAT-ACCT-ID PIC 9(11))',
  card_num                STRING
                          COMMENT 'Card number from XREF lookup (NULL if account not in XREF)',

  -- Rate lookup context
  dis_acct_group_id       STRING
                          COMMENT 'Account group used for rate lookup (or DEFAULT if fallback used)',
  tran_type_cd            STRING
                          COMMENT 'Transaction type code — always 01 for interest charges',
  tran_cat_cd             INT
                          COMMENT 'Transaction category code for this interest row',

  -- Interest calculation inputs and results
  tran_cat_bal_basis      DECIMAL(11,2)
                          COMMENT 'TRAN-CAT-BAL: balance used as basis for interest calculation',
  dis_int_rate            DECIMAL(7,4)
                          COMMENT 'Annual interest rate from DISCGRP (e.g., 18.0000 = 18% p.a.)',
  monthly_interest        DECIMAL(11,2)
                          COMMENT 'WS-MONTHLY-INT = (TRAN-CAT-BAL * DIS-INT-RATE) / 1200 for this category',
  total_interest          DECIMAL(11,2)
                          COMMENT 'WS-TOTAL-INT: sum of all category interests for this account (matches tran_amt)',

  -- Partition columns (must be NOT NULL)
  charge_year             INT            NOT NULL
                          COMMENT 'Year of run_date — partition key',
  charge_month            INT            NOT NULL
                          COMMENT 'Month of run_date — partition key',

  -- Run context
  run_date                DATE
                          COMMENT 'PARM-DATE: the processing date used as TRAN-ID prefix',

  -- Gold metadata
  _gold_load_ts           TIMESTAMP      NOT NULL
                          COMMENT 'Timestamp when this audit row was written to Gold',
  _gold_pipeline_run_id   STRING         NOT NULL
                          COMMENT 'Databricks job run ID for this pipeline execution'
)
USING DELTA
PARTITIONED BY (charge_year, charge_month)
COMMENT 'Gold: Per-category interest charge audit trail generated by CBACT04C pipeline. '
        'One row per (account, tran_cat_cd) per run. '
        'Replaces COBOL SYSOUT DISPLAY output from paragraphs 1000-TCATBALF-GET-NEXT and 1300-B-WRITE-TX.';

-- Primary key constraint (not enforced — Delta does not enforce PKs)
ALTER TABLE carddemo.gold.interest_charges
  ADD CONSTRAINT pk_interest_charges PRIMARY KEY (tran_id, tran_cat_cd) NOT ENFORCED;

-- Table properties
ALTER TABLE carddemo.gold.interest_charges
  SET TBLPROPERTIES (
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true',
    'migrated_from' = 'COBOL_SYSOUT_CBACT04C',
    'source_program' = 'CBACT04C',
    'jcl_job' = 'INTCALC'
  );

-- Z-ORDER recommendation (run via OPTIMIZE after initial load and periodically):
-- OPTIMIZE carddemo.gold.interest_charges
--   ZORDER BY (acct_id, run_date);


-- =============================================================================
-- Silver layer tables are defined in the project-wide Delta spec and created
-- by upstream ingestion pipelines. CBACT04C reads and writes to:
--
--   carddemo.silver.tran_cat_balance   (READ driving file)
--   carddemo.silver.disclosure_group   (READ interest rates — broadcast join)
--   carddemo.silver.card_xref          (READ for TRAN-CARD-NUM)
--   carddemo.silver.account            (READ + MERGE update)
--   carddemo.silver.transaction        (MERGE insert interest transactions)
--
-- DDL for these Silver tables is in:
--   tech_specs/target-modern-stack/11-delta-table-specification.md
--   (sections 4.1, 4.6, 4.7, 4.5, and 4.x respectively)
-- =============================================================================
