"""
SQLAlchemy ORM models for `transactions` and related reference tables.

Source copybooks:
  app/cpy/CVTRA05Y.cpy — TRAN-RECORD (350 bytes)     → `transactions`
  app/cpy/CVTRA01Y.cpy — TRAN-CAT-BAL-RECORD (50 bytes) → `tran_cat_balances`
  app/cpy/CVTRA02Y.cpy — DIS-GROUP-RECORD (50 bytes)  → `disclosure_groups`

Source VSAM files:
  TRANSACT — primary browse by TRAN-ID (sequential keyset pagination)
  TCATBALF — composite key (ACCT-ID, TYPE-CD, CAT-CD)
  DISCGRP  — composite key (GROUP-ID, TYPE-CD, CAT-CD)

DB2 tables (direct relational mapping):
  TRANSACTION_TYPE → `transaction_types` (TR_TYPE CHAR(2) PK)
  TRANSACTION_TYPE_CATEGORY → `transaction_type_categories`
"""
from decimal import Decimal

from sqlalchemy import BigInteger, CheckConstraint, ForeignKey, Index, Integer, Numeric, SmallInteger, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


class TransactionType(Base):
    """
    Transaction type reference table.

    Maps to DB2 table CARDDEMO.TRANSACTION_TYPE.
    TRAN-TYPE-CD PIC X(02) — e.g., '01'=Purchase, '02'=Payment.
    """

    __tablename__ = "transaction_types"

    # TR_TYPE CHAR(2) PK — matches trantype.txt: '01','02',...
    type_cd: Mapped[str] = mapped_column(String(2), primary_key=True, comment="TR_TYPE CHAR(2)")

    # TR_DESCRIPTION VARCHAR(50)
    description: Mapped[str | None] = mapped_column(String(50), nullable=True, comment="TR_DESCRIPTION VARCHAR(50)")

    # Relationships
    categories: Mapped[list["TransactionTypeCategory"]] = relationship(
        "TransactionTypeCategory", back_populates="tran_type", lazy="select",
        cascade="all, delete-orphan", passive_deletes=True
    )


class TransactionTypeCategory(Base):
    """
    Transaction type category reference table.

    Maps to DB2 table CARDDEMO.TRANSACTION_TYPE_CATEGORY.
    Composite PK: (type_cd, category_cd).
    """

    __tablename__ = "transaction_type_categories"

    # TRC_TYPE_CODE CHAR(2) FK
    type_cd: Mapped[str] = mapped_column(
        String(2), ForeignKey("transaction_types.type_cd", ondelete="CASCADE"), primary_key=True, comment="TRC_TYPE_CODE CHAR(2)"
    )

    # TRC_TYPE_CATEGORY INT
    category_cd: Mapped[int] = mapped_column(
        SmallInteger, primary_key=True, comment="TRC_TYPE_CATEGORY SMALLINT"
    )

    # TRC_TYPE_DESC VARCHAR(50)
    description: Mapped[str | None] = mapped_column(String(50), nullable=True, comment="TRC_TYPE_DESC VARCHAR(50)")

    # Relationships
    tran_type: Mapped["TransactionType"] = relationship("TransactionType", back_populates="categories")


class Transaction(Base):
    """
    Transaction record.

    Maps to COBOL TRAN-RECORD (CVTRA05Y.cpy).
    TRAN-ID PIC X(16) is the primary key — generated by COBIL00C using
    account number + timestamp (see cobol_compat.generate_transaction_id).

    Browse pattern: STARTBR/READNEXT on TRAN-ID (sequential) maps to
    keyset pagination: WHERE tran_id >= :cursor ORDER BY tran_id LIMIT n.
    """

    __tablename__ = "transactions"
    __table_args__ = (
        # Index for browsing by card number (COTRN01C)
        Index("ix_transactions_card_num", "card_num"),
        # Index for account-level transaction queries
        Index("ix_transactions_acct_id", "acct_id"),
        # Index for timestamp-based queries
        Index("ix_transactions_orig_ts", "orig_ts"),
    )

    # TRAN-ID PIC X(16) — primary key
    tran_id: Mapped[str] = mapped_column(String(16), primary_key=True, comment="TRAN-ID PIC X(16)")

    # TRAN-TYPE-CD PIC X(02) — FK to transaction_types
    type_cd: Mapped[str | None] = mapped_column(
        String(2), ForeignKey("transaction_types.type_cd", ondelete="RESTRICT"),
        nullable=True, comment="TRAN-TYPE-CD PIC X(02)"
    )

    # TRAN-CAT-CD PIC 9(04)
    cat_cd: Mapped[int | None] = mapped_column(SmallInteger, nullable=True, comment="TRAN-CAT-CD PIC 9(04)")

    # TRAN-SOURCE PIC X(10)
    source: Mapped[str | None] = mapped_column(String(10), nullable=True, comment="TRAN-SOURCE PIC X(10)")

    # TRAN-DESC PIC X(100)
    description: Mapped[str | None] = mapped_column(String(100), nullable=True, comment="TRAN-DESC PIC X(100)")

    # TRAN-AMT PIC S9(09)V99 COMP-3
    amount: Mapped[Decimal] = mapped_column(
        Numeric(11, 2), nullable=False, default=Decimal("0.00"), comment="TRAN-AMT PIC S9(09)V99"
    )

    # TRAN-MERCHANT-ID PIC 9(09)
    merchant_id: Mapped[int | None] = mapped_column(Integer, nullable=True, comment="TRAN-MERCHANT-ID PIC 9(09)")

    # TRAN-MERCHANT-NAME PIC X(50)
    merchant_name: Mapped[str | None] = mapped_column(
        String(50), nullable=True, comment="TRAN-MERCHANT-NAME PIC X(50)"
    )

    # TRAN-MERCHANT-CITY PIC X(50)
    merchant_city: Mapped[str | None] = mapped_column(
        String(50), nullable=True, comment="TRAN-MERCHANT-CITY PIC X(50)"
    )

    # TRAN-MERCHANT-ZIP PIC X(10)
    merchant_zip: Mapped[str | None] = mapped_column(
        String(10), nullable=True, comment="TRAN-MERCHANT-ZIP PIC X(10)"
    )

    # TRAN-CARD-NUM PIC X(16) — FK to cards
    card_num: Mapped[str | None] = mapped_column(
        String(16), ForeignKey("cards.card_num", ondelete="RESTRICT"),
        nullable=True, comment="TRAN-CARD-NUM PIC X(16)"
    )

    # Denormalized account ID for fast account-level queries
    # Derived from card_xref during transaction posting (CBTRN01C)
    acct_id: Mapped[int | None] = mapped_column(
        BigInteger, ForeignKey("accounts.acct_id", ondelete="RESTRICT"),
        nullable=True, comment="Derived from XREF-ACCT-ID during posting"
    )

    # TRAN-ORIG-TS PIC X(26) — stored as string to preserve original format
    orig_ts: Mapped[str | None] = mapped_column(String(26), nullable=True, comment="TRAN-ORIG-TS PIC X(26)")

    # TRAN-PROC-TS PIC X(26)
    proc_ts: Mapped[str | None] = mapped_column(String(26), nullable=True, comment="TRAN-PROC-TS PIC X(26)")

    # Relationships
    tran_type: Mapped["TransactionType | None"] = relationship("TransactionType", lazy="select")
    card: Mapped["Card | None"] = relationship(
        "Card", back_populates="transactions", foreign_keys=[card_num], lazy="select"
    )
    account: Mapped["Account | None"] = relationship(
        "Account", back_populates="transactions",
        foreign_keys="[Transaction.acct_id]", lazy="select"
    )


class TranCatBalance(Base):
    """
    Transaction category balance record.

    Maps to COBOL TRAN-CAT-BAL-RECORD (CVTRA01Y.cpy).
    Composite primary key: (acct_id, type_cd, cat_cd).

    Used by CBTRN02C (batch merge) and CBACT04C (interest calculation).
    """

    __tablename__ = "tran_cat_balances"

    # TRANCAT-ACCT-ID PIC 9(11)
    acct_id: Mapped[int] = mapped_column(
        BigInteger, ForeignKey("accounts.acct_id", ondelete="CASCADE"),
        primary_key=True, comment="TRANCAT-ACCT-ID PIC 9(11)"
    )

    # TRANCAT-TYPE-CD PIC X(02)
    type_cd: Mapped[str] = mapped_column(String(2), primary_key=True, comment="TRANCAT-TYPE-CD PIC X(02)")

    # TRANCAT-CD PIC 9(04)
    cat_cd: Mapped[int] = mapped_column(SmallInteger, primary_key=True, comment="TRANCAT-CD PIC 9(04)")

    # TRAN-CAT-BAL PIC S9(09)V99 COMP-3
    balance: Mapped[Decimal] = mapped_column(
        Numeric(11, 2), nullable=False, default=Decimal("0.00"), comment="TRAN-CAT-BAL PIC S9(09)V99"
    )

    # Relationships
    account: Mapped["Account"] = relationship("Account", back_populates="tran_cat_balances")


class DisclosureGroup(Base):
    """
    Disclosure group (interest rate lookup) record.

    Maps to COBOL DIS-GROUP-RECORD (CVTRA02Y.cpy).
    Composite primary key: (group_id, type_cd, cat_cd).

    Used by CBACT04C to look up DIS-INT-RATE for interest calculation.
    DIS-INT-RATE PIC S9(04)V99 — e.g., 1999 stored = 19.99% annual rate.
    """

    __tablename__ = "disclosure_groups"

    # DIS-ACCT-GROUP-ID PIC X(10)
    group_id: Mapped[str] = mapped_column(String(10), primary_key=True, comment="DIS-ACCT-GROUP-ID PIC X(10)")

    # DIS-TRAN-TYPE-CD PIC X(02)
    type_cd: Mapped[str] = mapped_column(String(2), primary_key=True, comment="DIS-TRAN-TYPE-CD PIC X(02)")

    # DIS-TRAN-CAT-CD PIC 9(04)
    cat_cd: Mapped[int] = mapped_column(SmallInteger, primary_key=True, comment="DIS-TRAN-CAT-CD PIC 9(04)")

    # DIS-INT-RATE PIC S9(04)V99 — annual interest rate (e.g., 19.99 = 19.99%)
    interest_rate: Mapped[Decimal] = mapped_column(
        Numeric(6, 2), nullable=False, default=Decimal("0.00"),
        comment="DIS-INT-RATE PIC S9(04)V99 [annual rate %]"
    )
