"""Custom exception classes and handlers for the CardDemo backend."""

from app.exceptions.errors import (
    AccountNoChangesDetectedError,
    AccountNotFoundError,
    AdminRequiredError,
    CardNotFoundError,
    CardOptimisticLockError,
    CustomerNotFoundError,
    NoChangesDetectedError,
    NothingToPayError,
    ReportRequestNotFoundError,
    TransactionNotFoundError,
    TransactionTypeAlreadyExistsError,
    TransactionTypeHasDependentsError,
    TransactionTypeNoChangesError,
    TransactionTypeNotFoundError,
    TransactionTypeOptimisticLockError,
    UnauthorizedError,
    UserAlreadyExistsError,
    UserNotFoundError,
    ValidationError,
)

__all__ = [
    "UserNotFoundError",
    "UserAlreadyExistsError",
    "NoChangesDetectedError",
    "AdminRequiredError",
    "UnauthorizedError",
    "TransactionTypeNotFoundError",
    "TransactionTypeAlreadyExistsError",
    "TransactionTypeHasDependentsError",
    "TransactionTypeOptimisticLockError",
    "TransactionTypeNoChangesError",
    "AccountNotFoundError",
    "CustomerNotFoundError",
    "AccountNoChangesDetectedError",
    "CardNotFoundError",
    "CardOptimisticLockError",
    "TransactionNotFoundError",
    "NothingToPayError",
    "ReportRequestNotFoundError",
    "ValidationError",
]
